-- ------------------------------------------------
-- Project Title:	Project Ysgramor
-- Author:		Joey Gliebe
-- Started:		04-06-15
-- Version:		0.0
-- Description:		A text-based adventure game
-- ------------------------------------------------
-- Filename: 		start.lua
-- Created: 		05-12-15
-- Description: 	Shows the map for the game.
-- 			Allows access to areas.
-- ------------------------------------------------

